### ISSUE TITLE
Exception thrown while picking up exp points

### ISSUE THREAD

**Issue by metroyanno** [PrismarineJS/prismarine-physics#17]
I get the following exception that crashes mineflayer. So, what's happened: bot killed a creeper and got exp points, after that the bot crashed and every time it joins the server it crashes again

```
bot/node_modules/prismarine-physics/index.js:599
    this.depthStrider = boots && boots.nbt.value.Enchantments && boots.nbt.value.Enchantments.some(x => x.id === mcData.enchantmentsByName.depth_strider.id)
                                           ^

TypeError: Cannot read property 'value' of null
    at new PlayerState (bot/node_modules/prismarine-physics/index.js:599:44)
    at Timeout.doPhysics [as _onTimeout] (bot/node_modules/mineflayer/lib/plugins/physics.js:61:32)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
```

**Comment by IdanHo** [comment]
This was fixed in #16, @rom1504 you might want to create a release

**Comment by rom1504** [comment]
@IdanHo only thing to do to create a release is to push a "Release x.y.z"
commit containing package.json and history.md change.
If you create a pull request with that we only have to press "rebase and
merge" and it's done.
Could you do it?

**Comment by IdanHo** [comment]
yep, see #18

**Comment by IdanHo** [comment]
@metroyanno all you have to do now is update your prismarine-physics
