### ISSUE TITLE
Add a Example with a working bot

### ISSUE THREAD

**Issue by Myzumi** [PrismarineJS/prismarine-physics#33]
Please add a example how you would use this with mineflyer, the example given in the README dosent really help new people that don't know much about coding or other.

**Comment by Karang** [comment]
It is used in mineflayer by default, you don't have anything to do. What are you trying to do exactly ?

**Comment by Myzumi** [comment]
Then i read it a bit wrong, but im trying to do a ingame bot with mineflyer but it dosen't get moved by water or anything

**Comment by Karang** [comment]
It should work by default, open an issue in mineflayer with the code you tried (fill the template).
